<?php

use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;

class FixDbFields extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        $fix_tables_timestamps = [
            'activities',
            'activity_identifiers',
            'albums',
            'badminton_player_match_score',
            'badminton_player_rubber_score',
            'badminton_pointwise_score',
            'badminton_statistic',
            'badminton_stats',
            'basketball_player_matchwise_stats',
            'basketball_statistic',
            'cities',
            'coach',
            'coach_sports',
            'contactus',
            'countries',
            'cricket_overwise_score',
            'cricket_player_matchwise_stats',
            'cricket_statistic',
            'deals',
            'emails',
            'facility_profile',
            'facility_schedules',
            'facility_sport_station',
            'facility_sport_station_slots',
            'facility_sports',
            'followers',
            'hockey_matchwise_score',
            'hockey_player_matchwise_stats',
            'hockey_statistic',
            'infolists',
            'kabaddi_player_matchwise_stats',
            'kabaddi_score',
            'kabaddi_set_details',
            'kabaddi_statistics',
            'marketplace',
            'marketplace_categories',
            'marketplace_logs',
            'match_schedules',
            'match_schedules_referees',
            'match_schedules_rubber',
            'messages',
            'notifications',
            'organization',
            'organization_group_team_points',
            'organization_group_teams',
            'organization_groups',
            'organization_staffs',
            'otp',
            'page_blocks',
            'pages',
            'participants',
            'payment_gate_ways',
            'photos',
            'ratings',
            'referee',
            'referee_sports',
            'request',
            'soccer_matchwise_score',
            'soccer_player_matchwise_stats',
            'soccer_statistic',
            'sports',
            'sports_questions',
            'sports_questions_answers',
            'sports_questions_options',
            'squash_player_match_score',
            'squash_pointwise_score',
            'squash_statistic',
            'states',
            'substitute_records',
            'table_tennis_stats',
            'team_invite',
            'team_players',
            'teams',
            'tennis_player_match_score',
            'tennis_player_rubber_score',
            'tennis_pointwise_score',
            'tennis_sets',
            'tennis_sets_game',
            'tennis_statistic',
            'testimonials',
            'threads',
            'throwball_player_matchwise_stats',
            'throwball_score',
            'throwball_set_details',
            'throwball_statistics',
            'tournament_final_teams',
            'tournament_group_teams',
            'tournament_groups',
            'tournament_match_preferences',
            'tournament_parent',
            'tournaments',
            'tt_player_match_score',
            'tt_player_rubber_score',
            'tt_pointwise_score',
            'tt_statistic',
            'ultimate_frisbee_player_matchwise_stats',
            'ultimate_frisbee_statistic',
            'user_activities',
            'user_providers',
            'user_statistics',
            'users',
            'volleyball_player_matchwise_stats',
            'volleyball_score',
            'volleyball_set_details',
            'volleyball_statistics',
            'waterpolo_player_matchwise_stats',
            'waterpolo_statistic',

        ];

        $fix_tables_delete = [
            'activities',
            'activity_identifiers',
            'albums',
            'badminton_player_match_score',
            'badminton_player_rubber_score',
            'badminton_pointwise_score',
            'badminton_statistic',
            'badminton_stats',
            'basketball_player_matchwise_stats',
            'basketball_statistic',
            'coach',
            'coach_sports',
            'cricket_overwise_score',
            'cricket_player_matchwise_stats',
            'cricket_statistic',
            'deals',
            'facility_profile',
            'facility_schedules',
            'facility_sport_station',
            'facility_sport_station_slots',
            'facility_sports',
            'followers',
            'hockey_matchwise_score',
            'hockey_player_matchwise_stats',
            'hockey_statistic',
            'marketplace',
            'marketplace_categories',
            'match_schedules',
            'match_schedules_rubber',
            'messages',
            'notifications',
            'organization',
            'participants',
            'photos',
            'ratings',
            'referee',
            'referee_sports',
            'request',
            'soccer_matchwise_score',
            'soccer_player_matchwise_stats',
            'soccer_statistic',
            'sports',
            'sports_questions',
            'sports_questions_answers',
            'sports_questions_options',
            'squash_player_match_score',
            'squash_pointwise_score',
            'squash_statistic',
            'substitute_records',
            'table_tennis_stats',
            'team_invite',
            'team_players',
            'teams',
            'tennis_player_match_score',
            'tennis_player_rubber_score',
            'tennis_pointwise_score',
            'tennis_statistic',
            'threads',
            'tournament_final_teams',
            'tournament_group_teams',
            'tournament_groups',
            'tournament_match_preferences',
            'tournament_parent',
            'tournaments',
            'tt_player_match_score',
            'tt_player_rubber_score',
            'tt_pointwise_score',
            'tt_statistic',
            'ultimate_frisbee_player_matchwise_stats',
            'ultimate_frisbee_statistic',
            'users',
            'waterpolo_player_matchwise_stats',
            'waterpolo_statistic',

        ];

        foreach ($fix_tables_timestamps as $tablename) {
            DB::statement("ALTER TABLE `$tablename` CHANGE COLUMN `created_at` `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP , CHANGE COLUMN `updated_at` `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP AFTER `created_at`");
        };

        foreach ($fix_tables_delete as $tablename) {
            DB::statement("ALTER TABLE `$tablename` ALTER `deleted_at` DROP DEFAULT");
            DB::statement("ALTER TABLE `$tablename` CHANGE COLUMN `deleted_at` `deleted_at` TIMESTAMP NULL AFTER `updated_at`");
        }
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {

    }
}
